/* Generated by Yosys 0.60 (git sha1 5bafeb77d, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "verilog/decoder.v:8.1-29.10" *)
module decoder(en, gain_sel, s1_n, s2_n, s3_n, s4_n);
  (* src = "verilog/decoder.v:9.23-9.25" *)
  input en;
  wire en;
  (* src = "verilog/decoder.v:10.23-10.31" *)
  input [1:0] gain_sel;
  wire [1:0] gain_sel;
  (* src = "verilog/decoder.v:11.23-11.27" *)
  output s1_n;
  wire s1_n;
  (* src = "verilog/decoder.v:12.23-12.27" *)
  output s2_n;
  wire s2_n;
  (* src = "verilog/decoder.v:13.23-13.27" *)
  output s3_n;
  wire s3_n;
  (* src = "verilog/decoder.v:14.23-14.27" *)
  output s4_n;
  wire s4_n;
  wire _0_;
  wire _1_;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _2_ (
    .I(gain_sel[1]),
    .ZN(_0_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _3_ (
    .I(en),
    .ZN(_1_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _4_ (
    .A1(gain_sel[0]),
    .A2(gain_sel[1]),
    .A3(_1_),
    .ZN(s1_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _5_ (
    .A1(gain_sel[0]),
    .A2(_0_),
    .A3(en),
    .Z(s2_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _6_ (
    .A1(gain_sel[0]),
    .A2(_0_),
    .A3(_1_),
    .ZN(s3_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _7_ (
    .A1(gain_sel[0]),
    .A2(gain_sel[1]),
    .A3(en),
    .Z(s4_n)
  );
endmodule
