/* Generated by Yosys 0.60 (git sha1 5bafeb77d, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "verilog/t_gate_driver.v:8.1-17.10" *)
module t_gate_driver(sN_n, nmos_gate, pmos_gate);
  (* src = "verilog/t_gate_driver.v:9.17-9.21" *)
  input sN_n;
  wire sN_n;
  (* src = "verilog/t_gate_driver.v:10.17-10.26" *)
  output nmos_gate;
  wire nmos_gate;
  (* src = "verilog/t_gate_driver.v:11.17-11.26" *)
  output pmos_gate;
  wire pmos_gate;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0_ (
    .I(sN_n),
    .ZN(pmos_gate)
  );
  assign nmos_gate = sN_n;
endmodule
