/* Generated by Yosys 0.60 (git sha1 5bafeb77d, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "verilog/window_detector.v:8.1-23.10" *)
module window_detector(comp_low, comp_high, in_window, alert_set, alert_reset);
  (* src = "verilog/window_detector.v:9.17-9.25" *)
  input comp_low;
  wire comp_low;
  (* src = "verilog/window_detector.v:10.17-10.26" *)
  input comp_high;
  wire comp_high;
  (* src = "verilog/window_detector.v:11.17-11.26" *)
  output in_window;
  wire in_window;
  (* src = "verilog/window_detector.v:12.17-12.26" *)
  output alert_set;
  wire alert_set;
  (* src = "verilog/window_detector.v:13.17-13.28" *)
  output alert_reset;
  wire alert_reset;
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0_ (
    .A1(comp_high),
    .A2(comp_low),
    .Z(alert_reset)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _1_ (
    .A1(comp_high),
    .A2(comp_low),
    .ZN(alert_set)
  );
  assign in_window = alert_reset;
endmodule
